#!/usr/bin/env bash
# Put the Gumbley AI brand onto this working tree.
#
#   scripts/branding/apply.sh            apply (idempotent)
#   scripts/branding/apply.sh --check    verify only; non-zero if anything drifted
#
# RUN THIS AFTER EVERY `git merge upstream/main`. It is the whole answer to
# "does the rebrand still hold?" — see BRANDING.md.
#
# What it does, in order:
#   1. concatenates branding/css/*.css into branding/static/custom.css
#   2. copies branding/static/ over static/static/ (the SvelteKit static dir,
#      which becomes build/static/ and then the app's /static/ route)
#   3. applies the three anchored name patches (scripts/branding/patch-source.py)
#
# Note that the DEPLOYED image does not need step 2 or 3: deploy/Dockerfile
# layers branding/static/ straight onto the official Open WebUI release and
# applies the same env.py patch. Step 2 and 3 are what make a build from THIS
# tree — including `npm run dev` — look the same as production.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$root"

check=0
[ "${1:-}" = "--check" ] && check=1

css_out="branding/static/custom.css"
overlay="branding/static"
dest="static/static"

fail=0
note() { printf '  %s  %s\n' "$1" "$2"; }
bad() { printf '  !  %s\n' "$1" >&2; fail=1; }

# ── 1. custom.css ────────────────────────────────────────────────────────────
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
	echo "/* GENERATED by scripts/branding/apply.sh from branding/css/*.css — do not edit. */"
	for f in branding/css/*.css; do
		printf '\n/* ===== %s ===== */\n' "${f#branding/css/}"
		cat "$f"
	done
} >"$tmp"

if [ "$check" = 1 ]; then
	if [ ! -f "$css_out" ] || ! cmp -s "$tmp" "$css_out"; then
		bad "$css_out is stale — run scripts/branding/apply.sh"
	else
		note "=" "$css_out up to date"
	fi
else
	cp "$tmp" "$css_out"
	note "+" "$css_out ($(wc -l <"$css_out") lines from $(ls branding/css/*.css | wc -l) sources)"
fi

# ── 2. overlay → static/static ───────────────────────────────────────────────
# Open WebUI keeps its own files in static/static/ (user.png, BRANDING.md,
# README.md, …). This copies ours over the top; it never deletes theirs.
copied=0
drift=0
while IFS= read -r -d '' src; do
	rel="${src#"$overlay"/}"
	tgt="$dest/$rel"
	if [ "$check" = 1 ]; then
		if [ ! -f "$tgt" ] || ! cmp -s "$src" "$tgt"; then
			bad "$tgt differs from $src"
			drift=$((drift + 1))
		fi
	else
		mkdir -p "$(dirname "$tgt")"
		cp "$src" "$tgt"
	fi
	copied=$((copied + 1))
done < <(find "$overlay" -type f -print0)

if [ "$check" = 1 ]; then
	[ "$drift" = 0 ] && note "=" "$copied overlay files match $dest/"
else
	note "+" "$copied overlay files → $dest/"
fi

# ── 3. anchored source patches ───────────────────────────────────────────────
echo
if [ "$check" = 1 ]; then
	python3 scripts/branding/patch-source.py --check || fail=1
else
	python3 scripts/branding/patch-source.py || fail=1
fi

# ── 4. CSS anchors still present upstream? ───────────────────────────────────
# branding/css/*.css hangs off a handful of ids. If one disappears in a merge
# the rules stop matching silently — the app looks stock rather than broken,
# which is exactly the failure you do not notice. Assert them.
echo
for anchor in \
	'src/routes/auth/+page.svelte:id="auth-page"' \
	'src/routes/auth/+page.svelte:id="auth-container"' \
	'src/routes/auth/+page.svelte:id="auth-login-card"' \
	'src/lib/components/chat/MessageInput.svelte:id="send-message-button"' \
	'src/app.html:/static/custom.css' \
	'src/app.html:/static/loader.js' \
	'src/tailwind.css:--app-font-family' \
	'src/tailwind.css:--color-gray-850'; do
	f="${anchor%%:*}"
	needle="${anchor#*:}"
	if grep -qF -- "$needle" "$f" 2>/dev/null; then
		note "=" "anchor ok   $needle"
	else
		bad "anchor GONE  $needle  (expected in $f)"
	fi
done

echo
if [ "$fail" != 0 ]; then
	echo "BRANDING DRIFT — see above. BRANDING.md explains each anchor." >&2
	exit 1
fi
echo "branding ok"
