#!/usr/bin/env bash
# Verify that a BUILT image is actually branded — not that the source tree is.
#
#   scripts/branding/verify-image.sh [image]      default: gumbley-ai:<deploy/.env version>
#
# Why this exists as well as `apply.sh --check`:
#
# The deployed image is the upstream release plus branding/static/ (see
# deploy/Dockerfile), so it is NOT built from this working tree and may be a
# different upstream version from it. Checking the tree therefore proves
# nothing about production. Every rule in branding/css/ hangs off an id or a
# custom property that has to exist in the BUILT frontend; if upstream renames
# one, the rule stops matching and the page quietly reverts to stock Open WebUI
# — no error, no broken layout, just the wrong colours. Nobody notices that
# from a health check.
#
# So this greps the image itself. Run it after every version bump, before
# `docker compose up -d`.
set -uo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# The compose project that names the running version lives in the private infra
# repo (see BRANDING.md), so this takes the tag as an argument and falls back to
# the Dockerfile's own default.
img="${1:-}"
if [ -z "$img" ]; then
	ver="$(sed -n 's/^ARG OPEN_WEBUI_VERSION=//p' deploy/Dockerfile | tail -1)"
	img="gumbley-ai:${ver:-0.11.3}"
fi

echo "verifying $img"
echo

# One container, one shell, all the greps — spawning per check would be slow
# and would not survive an image whose entrypoint refuses to be overridden.
# NOTE the exit-status check after this. Without it a docker failure (image
# absent, no permission on the socket) lands in $out, falls through the case
# below as an unrecognised line, and the script prints "image branding ok"
# having verified nothing at all.
out="$(docker run --rm --entrypoint sh "$img" -c '
  b=/app/build/static
  say() { printf "%s\t%s\n" "$1" "$2"; }

  # --- our files landed, and landed where the runtime copy reads from ---
  grep -q "GENERATED by scripts/branding/apply.sh" $b/custom.css 2>/dev/null \
    && say ok "custom.css is the Gumbley build" || say FAIL "custom.css is not ours"
  grep -q "Gumbley AI" $b/loader.js 2>/dev/null \
    && say ok "loader.js is the Gumbley build" || say FAIL "loader.js is not ours"
  [ -f $b/gumbleyai-logo.png ] && [ -f $b/gumbley-wordmark.png ] \
    && say ok "sign-in artwork present" || say FAIL "sign-in artwork missing"
  [ -d $b/fonts ] && [ "$(ls $b/fonts | wc -l)" -ge 7 ] \
    && say ok "self-hosted fonts present" || say FAIL "fonts missing"

  # --- the PWA install surface ---
  # EXTERNAL_PWA_MANIFEST_URL (set on the container, not baked into the image)
  # points the /manifest.json route at this file, and main.py raise_for_status()
  # es the fetch — so if it is absent the route 500s and the app stops being
  # installable at all. It must also be .json, not .webmanifest: that fetch is
  # aiohttp .json(), which rejects application/manifest+json.
  grep -q "\"Gumbley AI\"" $b/manifest.json 2>/dev/null \
    && say ok "PWA manifest is ours" || say FAIL "PWA manifest missing or not ours"
  # Every icon the manifest names has to exist, or the install UI falls back to
  # a screenshot of the page. Nothing errors when one is missing.
  miss=""
  for p in $(grep -o "/static/[A-Za-z0-9._-]*\.png" $b/manifest.json 2>/dev/null | sort -u); do
    [ -f "$b/${p#/static/}" ] || miss="$miss $p"
  done
  [ -n "$(grep -o "/static/[A-Za-z0-9._-]*\.png" $b/manifest.json 2>/dev/null)" ] \
    && { [ -z "$miss" ] && say ok "manifest icons all present" \
         || say FAIL "manifest icons missing:$miss"; } \
    || say FAIL "manifest declares no icons"
  # Upstream ships its own site.webmanifest naming the product "Open WebUI".
  # Nothing reads it, but it is public, so ours has to stay on top of it — and
  # this is exactly the check that catches it reappearing after an upgrade.
  # (No apostrophes anywhere in this heredoc-less block: the whole script body
  # is one single-quoted argument to `sh -c`, so one would end it early.)
  grep -q "\"Gumbley AI\"" $b/site.webmanifest 2>/dev/null \
    && say ok "site.webmanifest is ours" || say FAIL "site.webmanifest is the stock upstream file"

  # --- the name patch ---
  # Match the STATEMENT, not the string: the replacement leaves a comment
  # behind that mentions " (Open WebUI)" and a looser grep matches that.
  grep -q "WEBUI_NAME += " /app/backend/open_webui/env.py \
    && say FAIL "env.py still appends the name suffix" || say ok "env.py name suffix removed"

  # --- anchors the CSS depends on, in the BUILT frontend ---
  for id in auth-page auth-container auth-login-card send-message-button; do
    grep -rqF "$id" /app/build/_app 2>/dev/null \
      && say ok "anchor $id" || say FAIL "anchor $id GONE from the built app"
  done
  for v in --app-font-family --color-gray-850 --color-gray-950 --color-blue-400; do
    grep -rqF -e "$v" /app/build/_app 2>/dev/null \
      && say ok "anchor $v" || say FAIL "anchor $v GONE from the built CSS"
  done
' 2>&1)"
docker_rc=$?

if [ "$docker_rc" != 0 ]; then
	echo "  !  could not run $img (docker exit $docker_rc)" >&2
	printf '     %s\n' "$out" >&2
	echo >&2
	echo "VERIFICATION DID NOT RUN. This is a failure, not a pass." >&2
	exit 2
fi

rc=0
while IFS=$'\t' read -r status msg; do
	case "$status" in
	ok) printf '  =  %s\n' "$msg" ;;
	FAIL)
		printf '  !  %s\n' "$msg" >&2
		rc=1
		;;
	*)
		# Any line the container did not tag ok/FAIL is unexpected output —
		# treat it as a failure rather than printing it and passing.
		printf '  ?  unexpected: %s\n' "$status${msg:+ $msg}" >&2
		rc=1
		;;
	esac
done <<<"$out"

echo
if [ "$rc" != 0 ]; then
	echo "IMAGE NOT FULLY BRANDED — see above, and BRANDING.md for what each anchor is for." >&2
	exit 1
fi
echo "image branding ok"
